name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Checkout repository
      uses: actions/checkout@v3.3.0

    - name: Compute SHA
      run: >
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
        echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

    - name: Build container
      run: > 
        docker build .
        -t registry.digitalocean.com/go-team-heor/heor-intent-service:${{ env.SHORT_SHA }}
        -t registry.digitalocean.com/go-team-heor/heor-intent-service:latest
    - name: Log into registry
      run: doctl registry login --expiry-seconds 600
    - name: Push to DO
      run: docker push -a registry.digitalocean.com/go-team-heor/heor-intent-service
      
